# Generated by Django 6.0.3 on 2026-03-25 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_editorial', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.BigAutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=50, unique=True)),
                ('fecha_expedicion', models.DateField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credencial', to='gestion.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('stock_disponible', models.IntegerField(default=1)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='gestion.editorial')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('multa_generada', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.estudiante')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.libro')),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='estudiantes',
            field=models.ManyToManyField(related_name='libros_prestados', through='gestion.Prestamo', to='gestion.estudiante'),
        ),
    ]
